export interface Product {
  id: string;
  name: string;
  sku: string;
  category: string;
  price: number;
  originalPrice?: number;
  rating: number;
  reviewCount: number;
  stock: number;
  reorderPoint: number;
  inStock: boolean;
  isFeatured?: boolean;
  isTrending?: boolean;
  image: string;
  description: string;
  features: string[];
  specs: Record<string, string>;
  supplier: string;
}

export interface Category {
  id: string;
  name: string;
  slug: string;
  description: string;
  image: string;
  itemCount: number;
  growth: number;
}

export interface OrderItem {
  productId: string;
  productName: string;
  productImage: string;
  price: number;
  quantity: number;
}

export interface Order {
  id: string;
  customerName: string;
  customerEmail: string;
  date: string;
  total: number;
  status: 'Processing' | 'Shipped' | 'Delivered' | 'Cancelled';
  paymentMethod: string;
  shippingAddress: string;
  items: OrderItem[];
  trackingNumber?: string;
  estimatedDelivery?: string;
}

export interface Customer {
  id: string;
  name: string;
  email: string;
  avatar: string;
  ordersCount: number;
  totalSpent: number;
  joinDate: string;
  segment: 'VIP' | 'Regular' | 'New';
  location: string;
}

export interface InventoryItem {
  id: string;
  productName: string;
  sku: string;
  category: string;
  currentStock: number;
  reservedStock: number;
  reorderPoint: number;
  supplierName: string;
  status: 'Healthy' | 'Low Stock' | 'Critical Out';
  unitCost: number;
}

export interface Supplier {
  id: string;
  name: string;
  contactPerson: string;
  email: string;
  phone: string;
  category: string;
  leadTimeDays: number;
  rating: number;
  activeOrdersCount: number;
  status: 'Active' | 'Under Review';
}

export interface PipelineStage {
  id: string;
  name: string;
  layer: 'Source' | 'Ingestion' | 'Storage' | 'Processing' | 'Medallion' | 'Serving' | 'BI';
  tech: string;
  description: string;
  status: 'Active' | 'Idle' | 'Processing';
  throughput: string;
  latency: string;
  iconName: string;
  medallionTier?: 'Bronze' | 'Silver' | 'Gold';
  details: string[];
}

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Smart Electronics',
    slug: 'electronics',
    description: 'Next-gen audio, mechanical keyboards, fast GaN power adapters, and high-res mobile displays',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    itemCount: 6,
    growth: 18.4,
  },
  {
    id: 'cat-2',
    name: 'Workplace & Furniture',
    slug: 'furniture',
    description: 'Ergonomic smart office desks, cooling mesh task chairs, dual monitor mounts, and desk gear',
    image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=800&q=80',
    itemCount: 5,
    growth: 12.1,
  },
  {
    id: 'cat-3',
    name: 'Wearables & Fitness',
    slug: 'wearables',
    description: 'Biometric smartwatches, sleep tracking rings, smart body scales, and sport earbuds',
    image: 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=800&q=80',
    itemCount: 4,
    growth: 24.8,
  },
  {
    id: 'cat-4',
    name: 'Home Automation',
    slug: 'home-automation',
    description: 'Connected ambient RGB lighting, smart climate thermostats, and Wi-Fi 7 mesh routers',
    image: 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=800&q=80',
    itemCount: 3,
    growth: 9.3,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-101',
    name: 'Apex ANC Wireless Headphones',
    sku: 'SKU-APX-900',
    category: 'Smart Electronics',
    price: 24999,
    originalPrice: 29999,
    rating: 4.8,
    reviewCount: 142,
    stock: 48,
    reorderPoint: 15,
    inStock: true,
    isFeatured: true,
    isTrending: true,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    description: 'Flagship studio-grade noise-cancelling wireless headphones with 40-hour battery life and spatial audio response.',
    features: [
      'Active Noise Cancellation with 6 beamforming microphones',
      'Lossless LDAC & aptX HD audio codec streaming',
      '40-hour playback with fast-charge (10 min charge = 5 hours)',
      'Custom EQ adjustment via companion smartphone app',
    ],
    specs: {
      'Driver Unit': '40mm Titanium Dome',
      'Frequency Response': '5Hz - 40,000Hz',
      'Bluetooth Version': '5.3 LE Audio',
      'Weight': '254 grams',
    },
    supplier: 'Apex Audio Tech Ltd',
  },
  {
    id: 'prod-102',
    name: 'ErgoPro Motorized Standing Desk',
    sku: 'SKU-ERG-400',
    category: 'Workplace & Furniture',
    price: 54999,
    originalPrice: 62999,
    rating: 4.9,
    reviewCount: 98,
    stock: 12,
    reorderPoint: 10,
    inStock: true,
    isFeatured: true,
    image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=800&q=80',
    description: 'Dual-motor electric height-adjustable desk with solid walnut surface, digital memory presets, and wire management.',
    features: [
      'Dual whisper-quiet electric motors (<45dB)',
      'Four programmable height memory presets',
      'Integrated cable routing tray & power hub',
      'Anti-collision safety sensors',
    ],
    specs: {
      'Height Range': '62cm - 128cm',
      'Desktop Dimensions': '160cm x 80cm x 2.5cm',
      'Max Weight Capacity': '125 kg',
      'Warranty': '10 Years Frame',
    },
    supplier: 'Nordic Workspaces Inc',
  },
  {
    id: 'prod-103',
    name: 'PulseTrack Ultra Fitness Watch',
    sku: 'SKU-PLS-880',
    category: 'Wearables & Fitness',
    price: 17999,
    originalPrice: 19999,
    rating: 4.7,
    reviewCount: 210,
    stock: 8,
    reorderPoint: 20,
    inStock: true,
    isTrending: true,
    image: 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=800&q=80',
    description: 'Precision GPS smartwatch with multi-sport telemetry, SpO2 monitoring, electrocardiogram readiness, and 14-day battery.',
    features: [
      'Dual-frequency GNSS positioning (GPS, GLONASS, Galileo)',
      'Continuous heart rate, HRV, and sleep architecture tracking',
      '50m Water Resistance rating (5 ATM)',
      'OLED Sapphire Touchscreen Display',
    ],
    specs: {
      'Display': '1.43" AMOLED 466x466',
      'Battery': '450 mAh (14 Days typical)',
      'Sensors': 'Optical HR, ECG, SpO2, Barometer',
      'Compatibility': 'iOS 14+, Android 9.0+',
    },
    supplier: 'BioMetrics Global',
  },
  {
    id: 'prod-104',
    name: 'LuminaSmart RGB Ambient Light Bar',
    sku: 'SKU-LUM-220',
    category: 'Home Automation',
    price: 6999,
    originalPrice: 8999,
    rating: 4.6,
    reviewCount: 76,
    stock: 65,
    reorderPoint: 15,
    inStock: true,
    image: 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=800&q=80',
    description: 'Dynamic smart light bar syncing with screen content, music frequency, and home automation schedules via Wi-Fi.',
    features: [
      '16.8 Million RGBIC color matrix control',
      'Real-time screen color sync via HDMI/PC software',
      'Voice assistant support (Alexa, Google Assistant, Siri)',
      'Thread & Matter smart home standard compliant',
    ],
    specs: {
      'Luminous Flux': '800 Lumens',
      'Power Consumption': '18W',
      'Connectivity': 'Wi-Fi 2.4GHz + Bluetooth 5.0',
      'Lifespan': '30,000 Hours',
    },
    supplier: 'LuminaTech Systems',
  },
  {
    id: 'prod-105',
    name: 'QuantumKey Mechanical Wireless Keyboard',
    sku: 'SKU-QNT-710',
    category: 'Smart Electronics',
    price: 12999,
    originalPrice: 14999,
    rating: 4.9,
    reviewCount: 164,
    stock: 24,
    reorderPoint: 10,
    inStock: true,
    isTrending: true,
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',
    description: 'Hot-swappable gasket-mounted mechanical keyboard with CNC aluminum chassis and tri-mode connectivity.',
    features: [
      'Hot-swappable mechanical switches (Pre-lubed linear)',
      'Gasket mount architecture with 5-layer acoustic foam',
      'Tri-mode connectivity: 2.4GHz wireless, Bluetooth 5.1, USB-C',
      'Per-key South-facing RGB lighting',
    ],
    specs: {
      'Layout': '75% Compact (82 Keys)',
      'Body Material': 'Anodized CNC Aluminum',
      'Battery': '4000 mAh (200 hours without RGB)',
      'Weight': '1.45 kg',
    },
    supplier: 'Apex Audio Tech Ltd',
  },
  {
    id: 'prod-106',
    name: 'AeroGlide Ergonomic Mesh Task Chair',
    sku: 'SKU-ARG-550',
    category: 'Workplace & Furniture',
    price: 34999,
    originalPrice: 39999,
    rating: 4.7,
    reviewCount: 88,
    stock: 4,
    reorderPoint: 8,
    inStock: true,
    image: 'https://images.unsplash.com/photo-1505797149-43b0069ec26b?auto=format&fit=crop&w=800&q=80',
    description: 'Full breathable mesh task chair featuring dynamic lumbar tracking, 4D adjustable armrests, and weight-activated recline.',
    features: [
      'Self-adjusting dynamic lumbar support matrix',
      '4D multidirectional armrests with soft PU padding',
      'High-tension breathable cooling mesh',
      'Class 4 heavy-duty gas lift cylinder',
    ],
    specs: {
      'Recline Angle': '90° - 135° sync tilt',
      'Weight Capacity': '150 kg',
      'Base': 'Aluminum Alloy 5-Star Base',
      'Certifications': 'BIFMA Pass',
    },
    supplier: 'Nordic Workspaces Inc',
  },
  {
    id: 'prod-107',
    name: 'SoundCraft Pro Studio Monitors',
    sku: 'SKU-SND-800',
    category: 'Smart Electronics',
    price: 39999,
    originalPrice: 44999,
    rating: 4.9,
    reviewCount: 52,
    stock: 18,
    reorderPoint: 5,
    inStock: true,
    isFeatured: true,
    image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
    description: 'Bi-amplified active studio monitor pair with Kevlar drivers and acoustic room-tuning DSP controls.',
    features: [
      '5-inch Woven Kevlar low-frequency woofer',
      '1-inch Silk dome tweeter with waveguide',
      '70W Class D bi-amplification per speaker',
      'Acoustic space tuning controls (0dB, -2dB, -4dB)',
    ],
    specs: {
      'Frequency Response': '42Hz - 22,000Hz',
      'Inputs': 'XLR Balanced, 1/4" TRS, RCA',
      'SPL Peak': '104 dB',
      'Dimensions': '285 x 185 x 225 mm',
    },
    supplier: 'Apex Audio Tech Ltd',
  },
  {
    id: 'prod-108',
    name: 'PowerPulse 140W GaN Ultra Fast Charger',
    sku: 'SKU-PWR-140',
    category: 'Smart Electronics',
    price: 4999,
    originalPrice: 6499,
    rating: 4.8,
    reviewCount: 310,
    stock: 80,
    reorderPoint: 25,
    inStock: true,
    isTrending: true,
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=80',
    description: 'Compact 4-port GaN III wall charger capable of fast charging laptops, tablets, and phones simultaneously.',
    features: [
      '140W max output with Power Delivery 3.1',
      'Gallium Nitride (GaN III) high-efficiency architecture',
      'Dynamic power distribution across 3x USB-C and 1x USB-A ports',
      'Over-temperature and surge protection',
    ],
    specs: {
      'Ports': '3x USB-C PD, 1x USB-A QC 4.0',
      'Input Voltage': '100-240V AC 50/60Hz',
      'Weight': '290 grams',
      'Efficiency': '95%',
    },
    supplier: 'CyberPulse Electronics',
  },
  {
    id: 'prod-109',
    name: 'UltraDock Pro 12-in-1 Thunderbolt 4 Dock',
    sku: 'SKU-DCK-120',
    category: 'Smart Electronics',
    price: 18999,
    originalPrice: 21999,
    rating: 4.7,
    reviewCount: 64,
    stock: 22,
    reorderPoint: 10,
    inStock: true,
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=800&q=80',
    description: 'Enterprise Thunderbolt 4 docking station supporting dual 4K 60Hz displays and 96W pass-through charging.',
    features: [
      'Dual 4K@60Hz or single 8K display support',
      '96W host laptop pass-through charging',
      '2.5Gbps Gigabit Ethernet port',
      'UHS-II SD & MicroSD card reader slots',
    ],
    specs: {
      'Interface': 'Thunderbolt 4 (40Gbps)',
      'Power Adapter': '180W DC included',
      'Chassis': 'Solid Anodized Aluminum',
      'OS Support': 'macOS 11+, Windows 10/11',
    },
    supplier: 'CyberPulse Electronics',
  },
  {
    id: 'prod-110',
    name: 'ViewFlex 16" Portable 4K OLED Monitor',
    sku: 'SKU-VFX-4K',
    category: 'Smart Electronics',
    price: 29999,
    originalPrice: 34999,
    rating: 4.8,
    reviewCount: 41,
    stock: 14,
    reorderPoint: 5,
    inStock: true,
    isFeatured: true,
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80',
    description: 'Ultra-thin 16-inch 4K OLED portable display with 100% DCI-P3 color gamut and single USB-C cable operation.',
    features: [
      '4K UHD OLED panel with 100,000:1 contrast ratio',
      '100% DCI-P3 color space calibration',
      'Single USB-C video & power delivery cable',
      'Integrated magnetic cover & foldable kickstand',
    ],
    specs: {
      'Panel Size': '15.6 Inch OLED',
      'Resolution': '3840 x 2160',
      'Brightness': '400 nits',
      'Weight': '650 grams',
    },
    supplier: 'CyberPulse Electronics',
  },
  {
    id: 'prod-111',
    name: 'Horizon Dual Heavy-Duty Monitor Arm',
    sku: 'SKU-HRZ-ARM',
    category: 'Workplace & Furniture',
    price: 8999,
    originalPrice: 10999,
    rating: 4.6,
    reviewCount: 112,
    stock: 30,
    reorderPoint: 10,
    inStock: true,
    image: 'https://images.unsplash.com/photo-1593640408182-31c70c8268f5?auto=format&fit=crop&w=800&q=80',
    description: 'Gas-spring dual monitor arm supporting up to 32-inch displays with smooth 360-degree rotation.',
    features: [
      'Gas spring mechanical tension adjustment',
      'Supports dual monitors up to 32 inches (9kg per arm)',
      'VESA 75x75 & 100x100 quick release plates',
      'Integrated cable management channels',
    ],
    specs: {
      'Tilt Range': '+90° to -45°',
      'Swivel': '180°',
      'Rotation': '360°',
      'Mounting': 'C-Clamp & Grommet',
    },
    supplier: 'Nordic Workspaces Inc',
  },
  {
    id: 'prod-112',
    name: 'Artisan Top-Grain Leather Desk Mat',
    sku: 'SKU-ART-MAT',
    category: 'Workplace & Furniture',
    price: 2999,
    originalPrice: 3999,
    rating: 4.9,
    reviewCount: 185,
    stock: 50,
    reorderPoint: 15,
    inStock: true,
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80',
    description: 'Handcrafted full-grain leather desk pad with anti-slip suede backing and waterproof protective coating.',
    features: [
      '100% genuine top-grain cowhide leather',
      'Non-slip natural suede bottom lining',
      'Water-resistant matte seal layer',
      'Spacious 90cm x 40cm surface area',
    ],
    specs: {
      'Dimensions': '900 x 400 x 3 mm',
      'Material': 'Top-Grain Leather & Suede',
      'Edge': 'Precision Stitched',
    },
    supplier: 'Nordic Workspaces Inc',
  },
  {
    id: 'prod-113',
    name: 'NeatDesk Magnetic Cable Management Tray',
    sku: 'SKU-NTD-TRY',
    category: 'Workplace & Furniture',
    price: 1999,
    originalPrice: 2499,
    rating: 4.8,
    reviewCount: 95,
    stock: 40,
    reorderPoint: 10,
    inStock: true,
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&q=80',
    description: 'Under-desk steel cable tray with magnetic mounting clamps and open-weave heat ventilation.',
    features: [
      'No-drill magnetic clamp installation',
      'Heavy-duty powder-coated steel mesh',
      'Fits power strips up to 45cm long',
      'Includes 10 reusable Velcro cable ties',
    ],
    specs: {
      'Capacity': '10 kg',
      'Dimensions': '450 x 120 x 100 mm',
      'Finish': 'Matte Black Powder Coat',
    },
    supplier: 'Nordic Workspaces Inc',
  },
  {
    id: 'prod-114',
    name: 'BioRing Gen-3 Health & Sleep Tracker',
    sku: 'SKU-RNG-003',
    category: 'Wearables & Fitness',
    price: 21999,
    originalPrice: 24999,
    rating: 4.7,
    reviewCount: 130,
    stock: 16,
    reorderPoint: 8,
    inStock: true,
    isTrending: true,
    image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=80',
    description: 'Titanium smart ring monitoring continuous body temperature, HRV readiness, and sleep stage architecture.',
    features: [
      'Medical-grade PPG sensor array',
      'Skin temperature variation tracking',
      '7-day battery life on single wireless charge',
      'Water resistant to 100 meters (10 ATM)',
    ],
    specs: {
      'Material': 'Lightweight Titanium PVD',
      'Weight': '4 grams',
      'Battery': '7 Days Typical',
      'Waterproof': '100 Meters',
    },
    supplier: 'BioMetrics Global',
  },
  {
    id: 'prod-115',
    name: 'PrecisionBody Smart Wi-Fi Scale',
    sku: 'SKU-SCL-500',
    category: 'Wearables & Fitness',
    price: 4499,
    originalPrice: 5999,
    rating: 4.6,
    reviewCount: 220,
    stock: 35,
    reorderPoint: 12,
    inStock: true,
    image: 'https://images.unsplash.com/photo-1576678927484-cc909957088c?auto=format&fit=crop&w=800&q=80',
    description: 'Full-body composition scale measuring BFP, muscle mass, visceral fat, and heart rate with Wi-Fi auto-sync.',
    features: [
      'Dual-frequency BIA body composition sensors',
      'Tracks weight, body fat %, muscle mass, and water %',
      'Automatic user recognition for up to 8 profiles',
      'Color TFT screen displaying trend graphs',
    ],
    specs: {
      'Weight Capacity': '180 kg / 400 lbs',
      'Connectivity': 'Wi-Fi 2.4GHz + Bluetooth',
      'Surface': 'Tempered ITO Glass',
    },
    supplier: 'BioMetrics Global',
  },
  {
    id: 'prod-116',
    name: 'AeroFit Sport Noise-Canceling Earbuds',
    sku: 'SKU-AF-EAR',
    category: 'Wearables & Fitness',
    price: 9999,
    originalPrice: 11999,
    rating: 4.8,
    reviewCount: 175,
    stock: 28,
    reorderPoint: 10,
    inStock: true,
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
    description: 'IP68 sweatproof wireless earbuds with secure ear hooks, hybrid ANC, and transparency mode for runners.',
    features: [
      'IP68 dust, sweat, and waterproof protection',
      'Secure-fit wingtips for high-intensity workouts',
      '32 hours total playback with charging case',
      'Transparency mode for outdoor situational awareness',
    ],
    specs: {
      'Driver': '11mm Graphene Coated',
      'Playtime': '8 Hours + 24 Hours Case',
      'Bluetooth': 'Version 5.3',
    },
    supplier: 'BioMetrics Global',
  },
  {
    id: 'prod-117',
    name: 'ClimateSense Touch Smart Thermostat',
    sku: 'SKU-CLM-TST',
    category: 'Home Automation',
    price: 11999,
    originalPrice: 14999,
    rating: 4.7,
    reviewCount: 88,
    stock: 20,
    reorderPoint: 8,
    inStock: true,
    image: 'https://images.unsplash.com/photo-1567690187548-f07b1d7bf5a9?auto=format&fit=crop&w=800&q=80',
    description: 'Energy-saving smart thermostat with room occupancy sensors and AI schedule optimization.',
    features: [
      'Learns home heating & cooling habits in 1 week',
      'Includes 1 remote room temperature & motion sensor',
      'Saves estimated 15% on annual energy bills',
      'Works with Apple HomeKit, Alexa, and Google Home',
    ],
    specs: {
      'Screen': '3.5" Glass Touch Display',
      'Connectivity': 'Wi-Fi & Thread Mesh',
      'Compatibility': '95% of HVAC Systems',
    },
    supplier: 'LuminaTech Systems',
  },
  {
    id: 'prod-118',
    name: 'MeshForce 7 Tri-Band Wi-Fi 7 Router',
    sku: 'SKU-MSH-WFI7',
    category: 'Home Automation',
    price: 22999,
    originalPrice: 26999,
    rating: 4.9,
    reviewCount: 70,
    stock: 15,
    reorderPoint: 5,
    inStock: true,
    isTrending: true,
    image: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=800&q=80',
    description: 'Next-gen Wi-Fi 7 mesh router delivering ultra-fast 19Gbps wireless speeds and multi-link operation (MLO).',
    features: [
      'Wi-Fi 7 (802.11be) tri-band speeds up to 19 Gbps',
      '320 MHz channel width on 6GHz frequency band',
      'Dual 10Gbps WAN/LAN Ethernet ports',
      'Covers up to 3,500 sq ft per mesh node',
    ],
    specs: {
      'Bands': '2.4GHz, 5GHz, 6GHz',
      'Processor': 'Quad-Core 2.2GHz CPU',
      'Memory': '2GB RAM',
    },
    supplier: 'CyberPulse Electronics',
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ORD-2026-9041',
    customerName: 'Eleanor Vance',
    customerEmail: 'eleanor.vance@example.com',
    date: '2026-09-04 14:22',
    total: 948.00,
    status: 'Delivered',
    paymentMethod: 'Credit Card (Visa)',
    shippingAddress: '742 Evergreen Terrace, Seattle, WA 98101',
    trackingNumber: 'TRK-AZU-9921448',
    estimatedDelivery: '2026-09-03',
    items: [
      {
        productId: 'prod-101',
        productName: 'Apex ANC Wireless Headphones',
        productImage: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
        price: 299,
        quantity: 1,
      },
      {
        productId: 'prod-102',
        productName: 'ErgoPro Motorized Standing Desk',
        productImage: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=800&q=80',
        price: 649,
        quantity: 1,
      },
    ],
  },
  {
    id: 'ORD-2026-9042',
    customerName: 'Marcus Aurelius',
    customerEmail: 'marcus.aurelius@example.com',
    date: '2026-09-04 11:05',
    total: 378.00,
    status: 'Shipped',
    paymentMethod: 'Apple Pay',
    shippingAddress: '100 Palatine Hill Way, Austin, TX 78701',
    trackingNumber: 'TRK-AZU-9921449',
    estimatedDelivery: '2026-09-06',
    items: [
      {
        productId: 'prod-103',
        productName: 'PulseTrack Ultra Fitness Watch',
        productImage: 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=800&q=80',
        price: 219,
        quantity: 1,
      },
      {
        productId: 'prod-105',
        productName: 'QuantumKey Mechanical Wireless Keyboard',
        productImage: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',
        price: 159,
        quantity: 1,
      },
    ],
  },
  {
    id: 'ORD-2026-9043',
    customerName: 'Sophia Lin',
    customerEmail: 'sophia.lin@example.com',
    date: '2026-09-04 09:18',
    total: 299.00,
    status: 'Processing',
    paymentMethod: 'PayPal',
    shippingAddress: '450 Innovation Way, San Francisco, CA 94107',
    trackingNumber: 'TRK-AZU-9921450',
    estimatedDelivery: '2026-09-07',
    items: [
      {
        productId: 'prod-101',
        productName: 'Apex ANC Wireless Headphones',
        productImage: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
        price: 299,
        quantity: 1,
      },
    ],
  },
  {
    id: 'ORD-2026-9044',
    customerName: 'David Miller',
    customerEmail: 'david.miller@example.com',
    date: '2026-09-03 18:40',
    total: 518.00,
    status: 'Delivered',
    paymentMethod: 'Credit Card (Mastercard)',
    shippingAddress: '120 Market Street, Chicago, IL 60601',
    trackingNumber: 'TRK-AZU-9921445',
    estimatedDelivery: '2026-09-04',
    items: [
      {
        productId: 'prod-104',
        productName: 'LuminaSmart RGB Ambient Light Bar',
        productImage: 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=800&q=80',
        price: 89,
        quantity: 1,
      },
      {
        productId: 'prod-106',
        productName: 'AeroGlide Ergonomic Mesh Chair',
        productImage: 'https://images.unsplash.com/photo-1505797149-43b0069ec26b?auto=format&fit=crop&w=800&q=80',
        price: 429,
        quantity: 1,
      },
    ],
  },
];

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    name: 'Eleanor Vance',
    email: 'eleanor.vance@example.com',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    ordersCount: 14,
    totalSpent: 4820.00,
    joinDate: '2025-02-15',
    segment: 'VIP',
    location: 'Seattle, WA',
  },
  {
    id: 'cust-2',
    name: 'Marcus Aurelius',
    email: 'marcus.aurelius@example.com',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    ordersCount: 8,
    totalSpent: 2150.00,
    joinDate: '2025-06-10',
    segment: 'Regular',
    location: 'Austin, TX',
  },
  {
    id: 'cust-3',
    name: 'Sophia Lin',
    email: 'sophia.lin@example.com',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80',
    ordersCount: 3,
    totalSpent: 890.00,
    joinDate: '2026-01-20',
    segment: 'New',
    location: 'San Francisco, CA',
  },
  {
    id: 'cust-4',
    name: 'David Miller',
    email: 'david.miller@example.com',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    ordersCount: 19,
    totalSpent: 6410.00,
    joinDate: '2024-11-02',
    segment: 'VIP',
    location: 'Chicago, IL',
  },
];

export const MOCK_INVENTORY: InventoryItem[] = [
  {
    id: 'inv-1',
    productName: 'AeroGlide Ergonomic Mesh Task Chair',
    sku: 'SKU-ARG-550',
    category: 'Workplace & Furniture',
    currentStock: 4,
    reservedStock: 2,
    reorderPoint: 8,
    supplierName: 'Nordic Workspaces Inc',
    status: 'Low Stock',
    unitCost: 21000,
  },
  {
    id: 'inv-2',
    productName: 'PulseTrack Ultra Fitness Watch',
    sku: 'SKU-PLS-880',
    category: 'Wearables & Fitness',
    currentStock: 8,
    reservedStock: 4,
    reorderPoint: 20,
    supplierName: 'BioMetrics Global',
    status: 'Low Stock',
    unitCost: 9500,
  },
  {
    id: 'inv-3',
    productName: 'ErgoPro Motorized Standing Desk',
    sku: 'SKU-ERG-400',
    category: 'Workplace & Furniture',
    currentStock: 12,
    reservedStock: 3,
    reorderPoint: 10,
    supplierName: 'Nordic Workspaces Inc',
    status: 'Healthy',
    unitCost: 34000,
  },
  {
    id: 'inv-4',
    productName: 'Apex ANC Wireless Headphones',
    sku: 'SKU-APX-900',
    category: 'Smart Electronics',
    currentStock: 48,
    reservedStock: 10,
    reorderPoint: 15,
    supplierName: 'Apex Audio Tech Ltd',
    status: 'Healthy',
    unitCost: 14000,
  },
  {
    id: 'inv-5',
    productName: 'LuminaSmart RGB Ambient Light Bar',
    sku: 'SKU-LUM-220',
    category: 'Home Automation',
    currentStock: 65,
    reservedStock: 12,
    reorderPoint: 15,
    supplierName: 'LuminaTech Systems',
    status: 'Healthy',
    unitCost: 3800,
  },
  {
    id: 'inv-6',
    productName: 'QuantumKey Mechanical Wireless Keyboard',
    sku: 'SKU-QNT-710',
    category: 'Smart Electronics',
    currentStock: 24,
    reservedStock: 5,
    reorderPoint: 10,
    supplierName: 'Apex Audio Tech Ltd',
    status: 'Healthy',
    unitCost: 7500,
  },
  {
    id: 'inv-7',
    productName: 'SoundCraft Pro Studio Monitors',
    sku: 'SKU-SND-800',
    category: 'Smart Electronics',
    currentStock: 18,
    reservedStock: 4,
    reorderPoint: 5,
    supplierName: 'Apex Audio Tech Ltd',
    status: 'Healthy',
    unitCost: 24000,
  },
  {
    id: 'inv-8',
    productName: 'PowerPulse 140W GaN Ultra Fast Charger',
    sku: 'SKU-PWR-140',
    category: 'Smart Electronics',
    currentStock: 80,
    reservedStock: 15,
    reorderPoint: 25,
    supplierName: 'CyberPulse Electronics',
    status: 'Healthy',
    unitCost: 2800,
  },
  {
    id: 'inv-9',
    productName: 'UltraDock Pro 12-in-1 Thunderbolt 4 Dock',
    sku: 'SKU-DCK-120',
    category: 'Smart Electronics',
    currentStock: 22,
    reservedStock: 6,
    reorderPoint: 10,
    supplierName: 'CyberPulse Electronics',
    status: 'Healthy',
    unitCost: 11000,
  },
  {
    id: 'inv-10',
    productName: 'ViewFlex 16" Portable 4K OLED Monitor',
    sku: 'SKU-VFX-4K',
    category: 'Smart Electronics',
    currentStock: 14,
    reservedStock: 3,
    reorderPoint: 5,
    supplierName: 'CyberPulse Electronics',
    status: 'Healthy',
    unitCost: 18000,
  },
  {
    id: 'inv-11',
    productName: 'Horizon Dual Heavy-Duty Monitor Arm',
    sku: 'SKU-HRZ-ARM',
    category: 'Workplace & Furniture',
    currentStock: 30,
    reservedStock: 8,
    reorderPoint: 10,
    supplierName: 'Nordic Workspaces Inc',
    status: 'Healthy',
    unitCost: 5200,
  },
  {
    id: 'inv-12',
    productName: 'Artisan Top-Grain Leather Desk Mat',
    sku: 'SKU-ART-MAT',
    category: 'Workplace & Furniture',
    currentStock: 50,
    reservedStock: 10,
    reorderPoint: 15,
    supplierName: 'Nordic Workspaces Inc',
    status: 'Healthy',
    unitCost: 1600,
  },
  {
    id: 'inv-13',
    productName: 'NeatDesk Magnetic Cable Management Tray',
    sku: 'SKU-NTD-TRY',
    category: 'Workplace & Furniture',
    currentStock: 40,
    reservedStock: 6,
    reorderPoint: 10,
    supplierName: 'Nordic Workspaces Inc',
    status: 'Healthy',
    unitCost: 1100,
  },
  {
    id: 'inv-14',
    productName: 'BioRing Gen-3 Health & Sleep Tracker',
    sku: 'SKU-RNG-003',
    category: 'Wearables & Fitness',
    currentStock: 16,
    reservedStock: 4,
    reorderPoint: 8,
    supplierName: 'BioMetrics Global',
    status: 'Healthy',
    unitCost: 13000,
  },
  {
    id: 'inv-15',
    productName: 'PrecisionBody Smart Wi-Fi Scale',
    sku: 'SKU-SCL-500',
    category: 'Wearables & Fitness',
    currentStock: 35,
    reservedStock: 7,
    reorderPoint: 12,
    supplierName: 'BioMetrics Global',
    status: 'Healthy',
    unitCost: 2600,
  },
  {
    id: 'inv-16',
    productName: 'AeroFit Sport Noise-Canceling Earbuds',
    sku: 'SKU-AF-EAR',
    category: 'Wearables & Fitness',
    currentStock: 28,
    reservedStock: 5,
    reorderPoint: 10,
    supplierName: 'BioMetrics Global',
    status: 'Healthy',
    unitCost: 5800,
  },
  {
    id: 'inv-17',
    productName: 'ClimateSense Touch Smart Thermostat',
    sku: 'SKU-CLM-TST',
    category: 'Home Automation',
    currentStock: 20,
    reservedStock: 3,
    reorderPoint: 8,
    supplierName: 'LuminaTech Systems',
    status: 'Healthy',
    unitCost: 7200,
  },
  {
    id: 'inv-18',
    productName: 'MeshForce 7 Tri-Band Wi-Fi 7 Router',
    sku: 'SKU-MSH-WFI7',
    category: 'Home Automation',
    currentStock: 15,
    reservedStock: 2,
    reorderPoint: 5,
    supplierName: 'CyberPulse Electronics',
    status: 'Healthy',
    unitCost: 14000,
  },
];

export const MOCK_SUPPLIERS: Supplier[] = [
  {
    id: 'sup-1',
    name: 'Apex Audio Tech Ltd',
    contactPerson: 'Robert Sterling',
    email: 'supply@apexaudio.io',
    phone: '+1 (555) 234-8901',
    category: 'Smart Electronics',
    leadTimeDays: 4,
    rating: 4.9,
    activeOrdersCount: 5,
    status: 'Active',
  },
  {
    id: 'sup-2',
    name: 'Nordic Workspaces Inc',
    contactPerson: 'Freja Lindqvist',
    email: 'orders@nordicwork.se',
    phone: '+46 8 123 4567',
    category: 'Workplace & Furniture',
    leadTimeDays: 7,
    rating: 4.8,
    activeOrdersCount: 2,
    status: 'Active',
  },
  {
    id: 'sup-3',
    name: 'BioMetrics Global',
    contactPerson: 'David Chen',
    email: 'logistics@biometrics.com',
    phone: '+1 (555) 789-0123',
    category: 'Wearables & Fitness',
    leadTimeDays: 5,
    rating: 4.6,
    activeOrdersCount: 4,
    status: 'Active',
  },
];

export const MOCK_PIPELINE_STAGES: PipelineStage[] = [
  {
    id: 'p-1',
    name: 'Retail Application',
    layer: 'Source',
    tech: 'Next.js 15 / TypeScript',
    description: 'Generates real-time clickstream events, order transactions, and stock state updates.',
    status: 'Active',
    throughput: '12,400 events/sec',
    latency: '< 15 ms',
    iconName: 'ShoppingBag',
    details: ['REST & GraphQL event bus emitters', 'JSON Schema validation', 'Client session tracking'],
  },
  {
    id: 'p-2',
    name: 'Transactional Database',
    layer: 'Storage',
    tech: 'PostgreSQL / Azure Flexible Server',
    description: 'ACID transactional data store hosting operational tables and relational entities.',
    status: 'Active',
    throughput: '3,800 Write IOPS',
    latency: '< 8 ms',
    iconName: 'Database',
    details: ['WAL Change Data Capture (CDC)', 'Read-replicas for query scaling', 'SSL encrypted transit'],
  },
  {
    id: 'p-3',
    name: 'Azure Data Factory',
    layer: 'Ingestion',
    tech: 'ADF Pipeline Pipelines',
    description: 'Orchestrates scheduled batch ingestion & real-time event streaming triggers.',
    status: 'Active',
    throughput: '500 GB/day',
    latency: '1 min micro-batch',
    iconName: 'Workflow',
    details: ['Self-hosted Integration Runtimes', 'Automated retry policies', 'Managed VNet security'],
  },
  {
    id: 'p-4',
    name: 'ADLS Gen2 Landing Zone',
    layer: 'Storage',
    tech: 'Azure Data Lake Storage Gen2',
    description: 'Scalable hierarchical object storage acting as raw enterprise data landing pad.',
    status: 'Active',
    throughput: '1.2 TB total size',
    latency: 'Sub-second writes',
    iconName: 'FolderKanban',
    details: ['Hierarchical Namespace enabled', 'RBAC & ACL fine-grained auth', 'Lifecycle tiering rules'],
  },
  {
    id: 'p-5',
    name: 'Databricks + PySpark',
    layer: 'Processing',
    tech: 'Apache Spark / Delta Lake',
    description: 'Distributed compute engine processing raw telemetry into structured Medallion tables.',
    status: 'Active',
    throughput: '64 Worker Cores',
    latency: 'Sub-minute job cycle',
    iconName: 'Cpu',
    details: ['Delta Lake ACID compliance', 'Auto-scaling cluster management', 'PySpark ETL scripts'],
  },
  {
    id: 'p-6',
    name: 'Bronze Medallion Layer',
    layer: 'Medallion',
    medallionTier: 'Bronze',
    tech: 'Delta Lake Raw Stream',
    description: 'Raw unaltered copy of source payload with audit metadata timestamps.',
    status: 'Active',
    throughput: 'Immutable Append-only',
    latency: 'Instant sync',
    iconName: 'Layers',
    details: ['Preserves raw JSON payloads', 'Schema-on-read support', 'Full historical re-playability'],
  },
  {
    id: 'p-7',
    name: 'Silver Medallion Layer',
    layer: 'Medallion',
    medallionTier: 'Silver',
    tech: 'Cleaned & Joined Delta Tables',
    description: 'Deduplicated, schema-enforced, data-cleansed enterprise entities.',
    status: 'Active',
    throughput: 'Cleaned 99.98% quality',
    latency: 'Scheduled refresh',
    iconName: 'ShieldCheck',
    details: ['Great Expectations validation', 'Deduplication by Transaction ID', 'Type coercion & parsing'],
  },
  {
    id: 'p-8',
    name: 'Gold Medallion Layer',
    layer: 'Medallion',
    medallionTier: 'Gold',
    tech: 'Aggregated Star Schema',
    description: 'Dimensional models, fact tables, and aggregated business metrics for BI.',
    status: 'Active',
    throughput: 'Optimized Parquet/Delta',
    latency: '5 min refresh',
    iconName: 'Award',
    details: ['Fact_Sales & Dim_Customer models', 'SCD Type II tracking', 'Optimized Z-Ordering index'],
  },
  {
    id: 'p-9',
    name: 'Azure Synapse Analytics',
    layer: 'Serving',
    tech: 'Synapse Dedicated SQL Pool',
    description: 'Enterprise enterprise data warehouse serving sub-second analytical queries.',
    status: 'Active',
    throughput: '1,000 DWUs',
    latency: '< 150 ms query time',
    iconName: 'Server',
    details: ['Distributed Hash tables', 'Columnstore indexing', 'Synapse Studio SQL workspace'],
  },
  {
    id: 'p-10',
    name: 'Power BI Dashboards',
    layer: 'BI',
    tech: 'Power BI DirectQuery / Embedded',
    description: 'Interactive executive reporting, KPI dashboards, and automated email digests.',
    status: 'Active',
    throughput: 'DirectQuery mode',
    latency: 'Real-time dashboard',
    iconName: 'BarChart3',
    details: ['RLS (Row Level Security)', 'Embedded analytics SDK', 'Automated alert thresholds'],
  },
];

export const MOCK_REVENUE_TREND = [
  { month: 'Jan', revenue: 142000, orders: 1240, target: 130000 },
  { month: 'Feb', revenue: 158000, orders: 1380, target: 140000 },
  { month: 'Mar', revenue: 189000, orders: 1650, target: 150000 },
  { month: 'Apr', revenue: 176000, orders: 1520, target: 160000 },
  { month: 'May', revenue: 210000, orders: 1840, target: 175000 },
  { month: 'Jun', revenue: 245000, orders: 2150, target: 190000 },
  { month: 'Jul', revenue: 232000, orders: 2010, target: 200000 },
  { month: 'Aug', revenue: 278000, orders: 2420, target: 220000 },
  { month: 'Sep', revenue: 312000, orders: 2750, target: 250000 },
];

export const MOCK_CATEGORY_SALES = [
  { name: 'Smart Electronics', sales: 485000, percentage: 38 },
  { name: 'Workplace & Furniture', sales: 342000, percentage: 27 },
  { name: 'Wearables & Fitness', sales: 270000, percentage: 21 },
  { name: 'Home Automation', sales: 178000, percentage: 14 },
];
